server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8090
  connection-timeout: 5000ms

spring:
  http:
    encoding:
      charset: utf-8
      enabled: true